# -*- coding: utf-8 -*-
"""TimeSeriesProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zSllqP8o3gDAUjndF4tNmeR1lKn_Gh4h
"""

pip install mne

"""## 1. Import thư viện"""

import mne
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import signal
from statsmodels.tsa.stattools import adfuller
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.ar_model import AutoReg
from statsmodels.tsa.arima.model import ARIMA

"""## 2. Tải data lên"""

raw_fname = "/content/drive/MyDrive/mne_data/MNE-brainstorm-data/bst_raw/MEG/bst_raw/subj001_somatosensory_20111109_01_AUX-f.ds"
raw = mne.io.read_raw_ctf(raw_fname, preload=True)
raw.pick_types(eeg=True, meg=False).pick_channels(['EEG057'])

"""## 3. Plot đầu tiên"""

raw.plot(duration=5)

"""## 4. Lọc dữ liệu và EDA

- Lọc dữ liệu
"""

raw_eeg = raw.copy().pick_types(eeg=True, meg=False)

raw_band = raw_eeg.copy().filter(
    l_freq=1,
    h_freq=40,
    method='fir',
    phase='zero'
)
raw_clean = raw_band.copy().notch_filter(
    freqs=50,
    method='fir'
)

data = raw_clean.get_data()[0]

blink_threshold = 120e-6
blink_idx = np.where(np.abs(data) > blink_threshold)[0]

muscle_idx = np.where(np.abs(np.diff(data)) > 20e-6)[0]

annotations = []

for i in blink_idx:
    annotations.append((raw_clean.times[i], 0.2, 'BAD_blink'))

for i in muscle_idx:
    annotations.append((raw_clean.times[i], 0.1, 'BAD_muscle'))

annot = mne.Annotations(
    onset=[a[0] for a in annotations],
    duration=[a[1] for a in annotations],
    description=[a[2] for a in annotations]
)

raw_clean.set_annotations(annot)

"""- Plot sau khi lọc"""

sfreq = raw_clean.info["sfreq"]

duration_sec = 10

start = 0
end = int(duration_sec * sfreq)

times = raw_clean.times[start:end]

for ch in raw_clean.ch_names:
    data = raw_clean.get_data(picks=[ch])[0, start:end] * 1e6

    plt.figure(figsize=(10,3))
    plt.plot(times, data)
    plt.title(f"{ch} ({duration_sec}s)")
    plt.xlabel("Time (s)")
    plt.ylabel("Amplitude (µV)")
    plt.show()

"""- PSD"""

raw_clean.compute_psd(fmax=60).plot()

"""- Spectrogram"""

data = raw_clean.get_data()
data = data[0]

f57, t57, Sxx57 = signal.spectrogram(
    data,
    sfreq,
    nperseg=int(sfreq*2)
)

plt.figure(figsize=(10,5))
plt.pcolormesh(t57, f57, 10*np.log10(Sxx57), shading='gouraud')
plt.title("Spectrogram - EEG57")
plt.ylabel("Frequency (Hz)")
plt.xlabel("Time (s)")
plt.ylim(0, 60)
plt.colorbar(label="Power (dB)")
plt.show()

"""## 5.Stationarity checks; AR/MA/ARMA

- ADF
"""

def adf_test(timeseries):
    print("Results of Dickey-Fuller Test:")
    dftest = adfuller(timeseries, autolag="AIC", maxlag=50)
    dfoutput = pd.Series(
        dftest[0:4],
        index=[
            "Test Statistic",
            "p-value",
            "#Lags Used",
            "Number of Observations Used",
        ],
    )
    for key, value in dftest[4].items():
        dfoutput["Critical Value (%s)" % key] = value
    print(dfoutput)

adf_test(data)

"""- ACF & PACF"""

plot_acf(data, lags=range(100,110))
plt.title("ACF-EEG57")
plt.show()
plot_pacf(data, lags=10, method='ywm')
plt.title("PACF-EEG57")
plt.show()

"""- AR"""

modelAR = AutoReg(data, lags=2)
resultAR = modelAR.fit()

print(resultAR.summary())

"""- MA"""

modelMA = ARIMA(data, order=(0, 0, 2))
resultMA = modelMA.fit()

print(resultMA.summary())

"""- ARMA"""

modelARMA = ARIMA(data, order=(2, 0, 2))
resultARMA = modelARMA.fit()

print(resultARMA.summary())

"""###6. Model Selection"""

best_aic = np.inf
best_order = None

for p in range(0, 4):
    for q in range(0, 4):
        try:
            model = ARIMA(data[:30000], order=(p,0,q)).fit()
            if model.aic < best_aic:
                best_aic = model.aic
                best_order = (p,0,q)
        except:
            continue

print("Best order:", best_order)

"""###7. Residual"""

modelsel = AutoReg(data, lags=3)
resultsel = modelsel.fit()
residuals = resultsel.resid

"""Plot residuals"""

plt.plot(residuals)
plt.title("Residuals")
plt.show()

"""ACF residuals"""

plot_acf(residuals, lags=30)
plt.show()

"""###8. Forecasting"""

forecast = resultsel.forecast(steps=200)

plt.plot(data[:1000], label="Original")
plt.plot(range(1000, 1200), forecast, label="Forecast", color='red')
plt.legend()
plt.show()